"""Routes for the API"""

import secrets
import datetime
import base64
from io import BytesIO
from urllib.parse import urljoin

from flask import send_file, render_template, jsonify, redirect, request

from .utils import cap_gen
from app import limiter, captchas_solution, captcha_cdn, flask_app


def _id_generator(y: int) -> str:
    """
    Generates a captcha ID string of length 'y'.

    Args:
        y (int): The length of the captcha ID string to be generated.

    Returns:
        str: The captcha ID string of length 'y' generated by calling the 'choice' function on the given sequence of
            characters.

    """
    string = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKMNOPQRSTUVWXYZ"
    return "".join(secrets.choice(string) for _ in range(y))


def _b64_encrypt_id():
    """
    Encrypt given ID into base64.

    Decrypting this returns the captcha amount to date and the milisecond it was created
    """
    now = datetime.datetime.utcnow()
    time_now = now.strftime("%S")[-5:]

    return base64.b64encode(
        bytes(
            f"{flask_app.captcha_count}.{_id_generator(y=10)}.{time_now}",
            "utf-8",
        )
    ).decode()


@flask_app.route("/api/v5/cdn/<key>", methods=["GET"])
@limiter.limit("30/minute")
def get_img(key: str):
    """
    A Content Delivery Network (CDN) for serving captcha images.

    Args:
        key (str): The captcha identifier for which the image needs to be served.

    Returns:
        PIL.Image.Image: The captcha image corresponding to the given identifier.

    """
    try:
        if captcha_cdn[key]["accessed"] >= captcha_cdn[key]["max_access"]:
            del captcha_cdn[key]

        captcha_cdn[key]["accessed"] += 1

        if not captcha_cdn[key]["image"]:
            pil_image = cap_gen(text=captcha_cdn[key]["solution"])
            captcha_cdn[key]["image"] = pil_image
        else:
            pil_image = captcha_cdn[key]["image"]

        output = BytesIO()
        pil_image.convert("RGBA").save(output, format="PNG")
        output.seek(0, 0)

        return send_file(output, mimetype="image/png", as_attachment=False)

    except KeyError:
        return redirect("/")


@flask_app.route("/api/v5/captcha", methods=["GET"])
@limiter.limit("30/minute")
def api_captcha():
    """
    Endpoint for creating a dictionary key with the captcha ID and its related information. This route has an argument
    which indicates times the captcha image can be accessed before it is wiped from the dictionary.

    Two different types of cached dictionaries are stored,
        - captcha_cdn
        - captcha_solution

    Both have similar data but different access points (keys). This is so that the user cannot bruteforce the API
    directly. captcha_cdn key is shown (in CDN url) while captcha_solution is hidden.

    Returns:
        dict: A JSON dictionary containing the captcha ID and its related information.

    """
    access = request.args.get("requests", default=5, type=int)

    if access > 20:
        return redirect("/")

    solution_id = _b64_encrypt_id()
    solution = _id_generator(y=secrets.choice((4, 5)))
    captchas_solution[solution_id] = solution

    delta = datetime.timedelta(minutes=5)
    now = datetime.datetime.utcnow()
    cdn_id = _b64_encrypt_id()
    captcha_cdn[cdn_id] = {
        "solution": solution,
        "image": None,
        "time": now + delta,
        "accessed": 0,
        "max_access": access
    }

    flask_app.captcha_count += 1

    return jsonify(
        {
            "cdn_url": urljoin(request.host_url, f"/api/v5/cdn/{cdn_id}"),
            "solution_check_url": urljoin(
                request.host_url, f"/api/v5/check/{solution_id}"
            ),
            "solution_id": solution_id,
            "cdn_id": cdn_id,
        }
    )


@flask_app.route("/api/v5/check/<solution_id>", methods=["POST"])
@limiter.limit("10/minute")
def check_solution(solution_id: str):
    data = {"case_sensitive_correct": False, "case_insensitive_correct": False}

    attempt = request.args.get("solution", type=str, default="x")
    solution = captchas_solution.get(solution_id)

    if attempt == solution:  # type: ignore
        data["case_sensitive_correct"] = True

    if attempt.lower() == solution.lower():  # type: ignore
        data["case_insensitive_correct"] = True

    return jsonify(data)


@flask_app.route("/examples", methods=["GET"])
def examples():
    """API examples endpoint"""
    return render_template("examples.html")


@flask_app.route("/", methods=["GET"])
def home():
    """API home"""
    return render_template("index.html")


@flask_app.errorhandler(404)
def not_found(_):
    """404 error handling"""
    return redirect("/")
